### ISSUE TITLE
PLCrashReporter code is out of date and doesn't compile with Xcode 6.3

### ISSUE THREAD

**Issue by floatplane** [AppBlade/AppBladeSDK#97]
This compile issue was fixed in PLCrashReporter [about a year ago](https://opensource.plausible.coop/bugs/browse/PLCR-546) but the AppBlade SDK is pinned to an older version. Please update!

**Comment by jamesdaniels** [comment]
Whoops! I have a version I've been tracking that on and never pushed. Will get that updated shortly, sorry about that.

**Comment by floatplane** [comment]
Thanks @jamesdaniels!

**Comment by floatplane** [comment]
Hi, is there any progress to report on this issue?

**Comment by mtjhax** [comment]
Happy to announce the SDK is updated. Version 0.6.3 should compile with Xcode 6.3.x. A new binary release was also pushed. We will update our CocoaPod with the latest release shortly. If you have any issues please let us know.

**Comment by floatplane** [comment]
The new version still doesn't build from source with Xcode 6.3 :frowning:. The copy of PLCrashReporter you have doesn't seem to have the necessary change: https://github.com/plausiblelabs/plcrashreporter/commit/ad40dde8bd4f3fd6d13ffee5bf9a0dd309491525. 

Note how the `extern "C"` declaration is near the top of this file: https://github.com/AppBlade/AppBladeSDK/blob/master/iOS/Framework/AppBlade/CrashReporter/Source/PLCrashAsyncImageList.h, when it should be further down: https://github.com/plausiblelabs/plcrashreporter/blob/ad40dde8bd4f3fd6d13ffee5bf9a0dd309491525/Source/PLCrashAsyncImageList.h

**Comment by mtjhax** [comment]
How embarrassing, I neglected to 'git add' the majority of the updated PLCrashReporter files before pushing, which explains why it compiled for me. Please try again and my apologies.

**Comment by floatplane** [comment]
Thank you, builds fine now! Well, there's a tiny link error due to including a file in the library project that doesn't need to be there, I opened #99 for that. But this issue is resolved, thanks!
