### ISSUE TITLE
Pod install - spec not found

### ISSUE THREAD

**Issue by russellbstephens** [AppBlade/AppBladeSDK#98]
[!] Unable to find a specification for 'appblade'.

I've tried using both

pod 'appblade'
&
pod 'appblade', :git => 'https://github.com/AppBlade/AppBladeSDK.git', :commit => '955a74d379a407d6d8f5b93f733de19281436e16'

**Comment by mtjhax** [comment]
Hey Russell, it appears that in CocoaPods version 0.37.0 they made pod names case-sensitive, so if you change to 'AppBlade' it will work again.

**Comment by russellbstephens** [comment]
Thanks that worked

**Comment by natecope** [comment]
I am having this problem. I tried the case sensitive fix, and still can't find it.

**Comment by mtjhax** [comment]
We'll check that out ASAP... haven't needed to load up the CocoaPod recently so something may have expired/moved/broken/etc.

**Comment by natecope** [comment]
Looks like we've got it worked out. We needed to use double quotes instead
of single quotes in the podfile.

thanks!
-nate

**Comment by mtjhax** [comment]
For what it's worth, a new project with the most recent version of cocoapods and a Podfile consisting only of `pod 'AppBlade'` worked properly. Not sure why yours required double quotes but that is good to keep in mind.
